name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '⚠️ BREAKING CHANGES ⚠️'
    labels:
      - 'pr-breaking'
  - title: 'Features/Enhancements'
    labels:
      - 'pr-feature'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'pr-bugfix'
      - 'bug'
  - title: 'Other'
    labels:
      - 'docs'
      - 'enhancement'

include-labels:
  - pr-breaking
  - pr-feature
  - enhancement
  - fix
  - pr-bugfix
  - bug
  - docs
exclude-labels:
  - pr-nochangelog
exclude-contributors:
  - github-actions
  - github-actions[bot]

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'pr-breaking'
  minor:
    labels:
      - 'pr-feature'
  patch:
    labels:
      - 'fix'
      - 'pr-bugfix'
      - 'bug'
      - 'enhancement'
  default: patch

template: |
  ## Changes

  $CHANGES
